### ISSUE TITLE
Issue with '\' characters in Az rest calls causing command failures.

### ISSUE THREAD

**Issue by alaurie** [microsoft/azure-data-services-go-fast-codebase#277]
We had an issue with the Az calls in the ADF, Synapse and App service scripts. The commands have back slashes in the header parameters. These had to be removed before the command would complete successfully.

Error Example:
`$result = az rest --method post --uri "https://graph.microsoft.com/v1.0/servicePrincipals/$authappobjectid/appRoleAssignedTo" --headers '{\"Content-Type\":\"application/json\"}' --body $body`

Fixed Example:
`$result = az rest --method post --uri "https://graph.microsoft.com/v1.0/servicePrincipals/$authappobjectid/appRoleAssignedTo" --headers '{"Content-Type":"application/json"}' --body $body`

**Comment by jrampono** [comment]
Hi there, thanks for raising this. This issue is due to a Powershell version upgrade and will be addressed in the next release. For now, you can downgrade the Powershell version in your container. See this link for details: https://github.com/microsoft/azure-data-services-go-fast-codebase/releases/tag/v2.0.1
